# Generated by Django 5.2.4 on 2025-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
